name: BeagleApp
packages:
    ViewInspector:
        url: https://github.com/nalexn/ViewInspector
        version: "0.9.1"
    SnapshotTesting:
        url: https://github.com/pointfreeco/swift-snapshot-testing.git
        version: "1.10.0"
    Beagle:
        url: https://github.com/ZupIT/beagle-ios.git
        version: "2.1.1"
targets:
    BeagleApp:
        type: application
        platform: iOS
        deploymentTarget: "13.0"
        sources: [App]
        settings:
            base:
                INFOPLIST_FILE: App/Info.plist
                ENTITLEMENTS_FILE: App/App.entitlements
                PRODUCT_BUNDLE_IDENTIFIER: com.codename.ios.beagle.app
        scheme:
            testTargets:
                - BeagleAppTests
            gatherCoverageData: true
        dependencies:
            - package: Beagle
    BeagleAppTests:
        type: bundle.unit-test
        platform: iOS
        deploymentTarget: "13.0"
        sources:
            - path: AppTests
              excludes:
                - ReferenceImages/**
        settings:
            base:
                INFOPLIST_FILE: AppTests/Info.plist
        dependencies:
            - target: BeagleApp
            - package: ViewInspector
            - package: SnapshotTesting
